### ISSUE TITLE
Converting Part 629 Ex. A into JSON artifacts

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilKnowledgeBase#28]
A collection of code used to generate potential JSON artifacts to support linking to the GDS. Originally created to support work in SoilWeb and as a demonstration to the soil ontology crowd. Output currently generated from static (TXT) clips from 629 ex. A (minor editing for typos), but should be based on the GDS data provided by SKB.

PR: #27

Example output.
```
"back-barrier flat": {
    "def": [
      {
        "text": "A subaerial, gently sloping landform on the lagoon side of the barrier beach ridge composed predominantly of sand washed over or through the beach ridge during tidal surges; a portion of a barrier flat.",
        "compare": "Compare – washover-fan flat.",
        "sources": ["SS", "SSS"]
      }
    ]
  }
```

**Comment by brownag** [comment]
This has been addressed. The "GDS glossary" terms are parsed alphabetically into JSON files stored in the inst/extdata/NSSH/629 folder

I added several more data elements that were parseable from 629:
- whether the term is considered colloquial
- where the term is used,
- if it is considered "obsolete"
- and preferred terms (if any)

For instance:

https://github.com/ncss-tech/SoilKnowledgeBase/blob/03ad02b1351121aca4cacdc9ebc9f8f9736932cd/inst/extdata/NSSH/629/GDS-glossary-B.json#L38-L49

or 

https://github.com/ncss-tech/SoilKnowledgeBase/blob/c8f6b58861a955b8d07721155231d458f9a6eb38/inst/extdata/NSSH/629/GDS-glossary-B.json#L134-L145

629 gets pretty particular about the meaning of preferred, obsolete etc. so the full nuance of each entry may not be captured, and I think there are a couple colloquial locations misparsed that need addressing

**Comment by dylanbeaudette** [comment]
This is great, thanks for the substantial improvements.

**Comment by dylanbeaudette** [comment]
Good to close then, yes?
