### ISSUE TITLE
add "Additional Data" section to OSD parsing code / output

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilKnowledgeBase#38]
This is currently lumped into the "REMARKS" section.

**Comment by brownag** [comment]
That was by design, I think. 
Additional Data is not a required section in NSSH and is only on an as needed basis. We probably could parse it out but there are a variety of ways it gets called out. Will look into it.

**Comment by dylanbeaudette** [comment]
Ok thanks. I need to talk some more with SRSS about how their use / expectations for this field are.

**Comment by brownag** [comment]
So, about 1/3 (n=8639) of the OSDs have a readily parse-able ADDITIONAL DATA section--definitely worth trying to separate it out. I'll be messing around with some of my core logic around the last sections / end of file handling in this PR: https://github.com/ncss-tech/SoilKnowledgeBase/pull/40

**Comment by brownag** [comment]
Additional Data section has been added, and Tabular Series Data where present are considered to be a type of additional data.
