### ISSUE TITLE
parse errors due to non-standard typical pedon section header

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilKnowledgeBase#49]
```r
c("ARIEL", "COLEMANTOWN", "DOCENA", "DUCKBOTTOM", "FIDDLETOWN", 
"GAPPMAYER", "GORING", "GREENWICH", "GUALALA", "HARKERS", "HATU", 
"LEIPSIC", "LUCKETTS", "MAJURO", "MANOKIN", "MIMMS", "MISPILLION", 
"MOYERS", "OLANTA", "PACKSADDLE", "PINICON", "QUEPONCO", "QUINDOCQUA", 
"ROMIA", "SABANA", "SCAPO", "SHOULDERBONE", "SIELO", "TENT", 
"TIZZARD", "TOLLGATE", "TRUSSUM", "TUSKAHOMA", "VELOW", "QUAKERBRIDGE", 
"LAKEHURST")
```
|OSD                                                                              |JSON                                                                                                               |
|:--------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------|
|[ARIEL](https://casoilresource.lawr.ucdavis.edu/sde/?series=ARIEL)               |[ARIEL.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/A/ARIEL.json)               |
|[COLEMANTOWN](https://casoilresource.lawr.ucdavis.edu/sde/?series=COLEMANTOWN)   |[COLEMANTOWN.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/C/COLEMANTOWN.json)   |
|[DOCENA](https://casoilresource.lawr.ucdavis.edu/sde/?series=DOCENA)             |[DOCENA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/D/DOCENA.json)             |
|[DUCKBOTTOM](https://casoilresource.lawr.ucdavis.edu/sde/?series=DUCKBOTTOM)     |[DUCKBOTTOM.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/D/DUCKBOTTOM.json)     |
|[FIDDLETOWN](https://casoilresource.lawr.ucdavis.edu/sde/?series=FIDDLETOWN)     |[FIDDLETOWN.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/F/FIDDLETOWN.json)     |
|[GAPPMAYER](https://casoilresource.lawr.ucdavis.edu/sde/?series=GAPPMAYER)       |[GAPPMAYER.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/G/GAPPMAYER.json)       |
|[GORING](https://casoilresource.lawr.ucdavis.edu/sde/?series=GORING)             |[GORING.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/G/GORING.json)             |
|[GREENWICH](https://casoilresource.lawr.ucdavis.edu/sde/?series=GREENWICH)       |[GREENWICH.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/G/GREENWICH.json)       |
|[GUALALA](https://casoilresource.lawr.ucdavis.edu/sde/?series=GUALALA)           |[GUALALA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/G/GUALALA.json)           |
|[HARKERS](https://casoilresource.lawr.ucdavis.edu/sde/?series=HARKERS)           |[HARKERS.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/H/HARKERS.json)           |
|[HATU](https://casoilresource.lawr.ucdavis.edu/sde/?series=HATU)                 |[HATU.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/H/HATU.json)                 |
|[LEIPSIC](https://casoilresource.lawr.ucdavis.edu/sde/?series=LEIPSIC)           |[LEIPSIC.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/L/LEIPSIC.json)           |
|[LUCKETTS](https://casoilresource.lawr.ucdavis.edu/sde/?series=LUCKETTS)         |[LUCKETTS.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/L/LUCKETTS.json)         |
|[MAJURO](https://casoilresource.lawr.ucdavis.edu/sde/?series=MAJURO)             |[MAJURO.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/M/MAJURO.json)             |
|[MANOKIN](https://casoilresource.lawr.ucdavis.edu/sde/?series=MANOKIN)           |[MANOKIN.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/M/MANOKIN.json)           |
|[MIMMS](https://casoilresource.lawr.ucdavis.edu/sde/?series=MIMMS)               |[MIMMS.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/M/MIMMS.json)               |
|[MISPILLION](https://casoilresource.lawr.ucdavis.edu/sde/?series=MISPILLION)     |[MISPILLION.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/M/MISPILLION.json)     |
|[MOYERS](https://casoilresource.lawr.ucdavis.edu/sde/?series=MOYERS)             |[MOYERS.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/M/MOYERS.json)             |
|[OLANTA](https://casoilresource.lawr.ucdavis.edu/sde/?series=OLANTA)             |[OLANTA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/O/OLANTA.json)             |
|[PACKSADDLE](https://casoilresource.lawr.ucdavis.edu/sde/?series=PACKSADDLE)     |[PACKSADDLE.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/P/PACKSADDLE.json)     |
|[PINICON](https://casoilresource.lawr.ucdavis.edu/sde/?series=PINICON)           |[PINICON.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/P/PINICON.json)           |
|[QUEPONCO](https://casoilresource.lawr.ucdavis.edu/sde/?series=QUEPONCO)         |[QUEPONCO.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/Q/QUEPONCO.json)         |
|[QUINDOCQUA](https://casoilresource.lawr.ucdavis.edu/sde/?series=QUINDOCQUA)     |[QUINDOCQUA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/Q/QUINDOCQUA.json)     |
|[ROMIA](https://casoilresource.lawr.ucdavis.edu/sde/?series=ROMIA)               |[ROMIA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/R/ROMIA.json)               |
|[SABANA](https://casoilresource.lawr.ucdavis.edu/sde/?series=SABANA)             |[SABANA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/S/SABANA.json)             |
|[SCAPO](https://casoilresource.lawr.ucdavis.edu/sde/?series=SCAPO)               |[SCAPO.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/S/SCAPO.json)               |
|[SHOULDERBONE](https://casoilresource.lawr.ucdavis.edu/sde/?series=SHOULDERBONE) |[SHOULDERBONE.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/S/SHOULDERBONE.json) |
|[SIELO](https://casoilresource.lawr.ucdavis.edu/sde/?series=SIELO)               |[SIELO.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/S/SIELO.json)               |
|[TENT](https://casoilresource.lawr.ucdavis.edu/sde/?series=TENT)                 |[TENT.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/T/TENT.json)                 |
|[TIZZARD](https://casoilresource.lawr.ucdavis.edu/sde/?series=TIZZARD)           |[TIZZARD.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/T/TIZZARD.json)           |
|[TOLLGATE](https://casoilresource.lawr.ucdavis.edu/sde/?series=TOLLGATE)         |[TOLLGATE.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/T/TOLLGATE.json)         |
|[TRUSSUM](https://casoilresource.lawr.ucdavis.edu/sde/?series=TRUSSUM)           |[TRUSSUM.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/T/TRUSSUM.json)           |
|[TUSKAHOMA](https://casoilresource.lawr.ucdavis.edu/sde/?series=TUSKAHOMA)       |[TUSKAHOMA.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/T/TUSKAHOMA.json)       |
|[VELOW](https://casoilresource.lawr.ucdavis.edu/sde/?series=VELOW)               |[VELOW.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/V/VELOW.json)               |
|[QUAKERBRIDGE](https://casoilresource.lawr.ucdavis.edu/sde/?series=QUAKERBRIDGE) |[QUAKERBRIDGE.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/Q/QUAKERBRIDGE.json) |
|[LAKEHURST](https://casoilresource.lawr.ucdavis.edu/sde/?series=LAKEHURST)       |[LAKEHURST.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/L/LAKEHURST.json)       |

**Comment by brownag** [comment]
I think a good addition to the OSD error reporting would be to parse the log files generated by each SKB refresh. This is something I always planned on implementing, but never integrated it with the newer post-processing scripts. SKB supports logging output for any of the create_* functions

Notably this would catch any OSDs using the "duplicated header" trick to put a bunch of extra front matter in, or any OSDs that are outright duplicated (it happens)

The .log files are generated on each run in a standard location (inst/extdata/OSD/OSD.log) but are not tracked in git. They have a standard format and the errors/names identified could be added to the types of errors we report on.

For example, OSD.log:
```
Processing OSD data snapshot from OSDRegistry...
Downloading snapshot...
 - OSD/A/AABAB.txt
 - OSD/A/AABERG.txt
 - OSD/A/AAGARD.txt
 - OSD/A/AARON.txt
 - OSD/A/AARUP.txt
 - OSD/A/AASTAD.txt
 - OSD/A/AAZDAHL.txt
 - OSD/A/ABAC.txt
 - OSD/A/ABAFT.txt
 - OSD/A/ABAJO.txt
 - OSD/A/ABALAN.txt
 - OSD/A/ABALOBADIAH.txt
 - OSD/A/ABARCA.txt
CHECK DUPLICATION OF HEADERS: OSD/A/ABARCA.txt
 - OSD/A/ABBAYE.txt
 - OSD/A/ABBEYLAKE.txt
```
