### ISSUE TITLE
OSD colors with common OCR errors 

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/SoilKnowledgeBase#53]
I can't remember, but thought that there were special cases in the REGEX to deal with:
   * 'lower-case L' → numeral `1`
   * 'upper-case O' → numeral `0`

This affects both horizon and Munsell color REGEX. There is a 'O' in the horizon detection, but not 'l, can't remember why. I've fixed the SYCAMORE OSD today, but I've added a test to the SKB tests to pickup similar errors. It is commented out for now.

I suspect that allowing `[O,l]` into the REGEX will solve the problem, but I don't have enough time right now to ensure that it won't break something else.

|OSD                                                                      |JSON                                                                                                       |
|:------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------|
|[SYCAMORE](https://casoilresource.lawr.ucdavis.edu/sde/?series=SYCAMORE) |[SYCAMORE.json](https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/S/SYCAMORE.json) |

**Comment by brownag** [comment]
Great thing to fix. Thanks for the PR. Should only require minor modification of the regex, barring a bunch of non-target impacts.

It looks like the patterns from parse OSD repo did not handle the L/O in colors, but there was handling for capital O versus zero for depths, and support for all letters and numbers in the designations (which should get stuff like `0i`)

https://github.com/ncss-tech/SoilKnowledgeBase/blob/df034010c3355aefb0ef9d47a5242ec7c3b0a586/misc/parseOSD-migration/local_functions.R#L548-L553

https://github.com/ncss-tech/SoilKnowledgeBase/blob/df034010c3355aefb0ef9d47a5242ec7c3b0a586/misc/parseOSD-migration/local_functions.R#L590-L594

**Comment by dylanbeaudette** [comment]
Thanks. The non-target impacts are what I worry about, given the huge range in formatting and typos.

**Comment by brownag** [comment]
I've updated the regexes to this. 

There were no non-target impacts in #54 but there are quite a few OSDs that had missing horizons due to not allowing `"l"` in the place of `1` or similar. Likewise, some horizons with more than dry/moist color now are parsing the correct color, with some components NA.

I will create another PR to close this issue; it will address  character->numeric corrections so the proper values come out in the JSON and refining the OSD error checking output as needed.

**Comment by brownag** [comment]
https://github.com/ncss-tech/SoilKnowledgeBase/blob/9fc94a0f3294905c6ca202c2c97c69b3cac688f9/R/parseOSD_functions.R#L284-L287

https://github.com/ncss-tech/SoilKnowledgeBase/blob/9fc94a0f3294905c6ca202c2c97c69b3cac688f9/R/parseOSD_functions.R#L326-L330

**Comment by brownag** [comment]
On second thought, the character->numeric corrections will be applied to the results of `soilDB::get_OSD()` via optional argument.

That way we have an accurate representation of the data in the repo, accurate reporting on errors based on that data, but also an option to do "obvious" fixes for the end user (need to "opt in" by setting argument)

**Comment by dylanbeaudette** [comment]
Nice, I like this compromise. Thanks.
